name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: npm
    
    - name: Cache Next.js build
      uses: actions/cache@v4
      with:
        path: ${{github.workspace}}/.next/cache
        key: ${{runner.os}}-nextjs-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Print environment variables
      run: printenv

    - name: Build the application
      env:
        FLAGSMITH_KEY: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT_KEY }}
        NEXT_PUBLIC_ENVIRONMENT_KEY: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT_KEY }}
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1  # Specify your AWS region

    - name: Deploy to Elastic Beanstalk
      env:
        EB_APP_NAME: ${{vars.EB_APP_NAME}}  # Replace with your Elastic Beanstalk application name
        EB_ENV_NAME: ${{vars.EB_APP_ENV}}  # Replace with your Elastic Beanstalk environment name
      run: |
        # Install EB CLI
        python -m pip install --upgrade pip
        pip install awsebcli

        # Initialize EB CLI
        eb init -p node.js -r us-east-1 $EB_APP_NAME

        # Deploy to Elastic Beanstalk
        eb deploy $EB_ENV_NAME
